B7.2.2.1 Задание
1 point possible (graded)
Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:


In [1]:
import numpy as np
import pandas as pd

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]
big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [20]:
my_array=big_secret[:,-1]
display(np.shape(big_secret))
display(my_array.sum())

(5, 51)

3154.332495807108

B7.2.2.2 Задание
1 point possible (graded)
Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [23]:
my_array=big_secret[:,:5]
display(np.shape(my_array))
sum_diag=my_array[0,0]+my_array[1,1]+my_array[2,2]+my_array[3,3]+my_array[4,4]
display(sum_diag)

(5, 5)

121.37188663699624

B7.2.2.3 Задание
1 point possible (graded)
Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [24]:
my_array=big_secret[:,-5:]
display(np.shape(my_array))
sum_diag=my_array[0,0]*my_array[1,1]*my_array[2,2]*my_array[3,3]*my_array[4,4]
display(sum_diag)

(5, 5)

341505315559.2347

Упражнения
Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

B7.2.2.4 Задание
1 point possible (graded)
Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [1]:
import numpy as np
import pandas as pd

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]
big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

x_row = big_secret.shape[0]
x_col = big_secret.shape[1]
for i in range(1, x_row, 2):
    for j in range(1, x_col, 2):
        big_secret[i, j] = 1
for i in range(0, x_row, 2):
    for j in range(0, x_col, 2):
        big_secret[i, j] = -1
display(big_secret)

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [27]:
my_array=big_secret[:,:5]
display(np.shape(my_array))
sum_diag=my_array[0,0]+my_array[1,1]+my_array[2,2]+my_array[3,3]+my_array[4,4]
display(sum_diag)

(5, 5)

-1.0

B7.2.2.5 Задание
1 point possible (graded)
Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [28]:
my_array=big_secret[:,-5:]
display(np.shape(my_array))
sum_diag=my_array[0,0]*my_array[1,1]*my_array[2,2]*my_array[3,3]*my_array[4,4]
display(sum_diag)

(5, 5)

-1.0

Упражнения
Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [4]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_secret = np.array([first, second, third]).T

Сколько столбцов содержит массив great_secret?

In [32]:
display(np.shape(great_secret))

(100, 3)

B7.2.3.2 Задание
1 point possible (graded)
Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [12]:
my_array=great_secret[0,]
display((my_array))
display(np.cos(my_array).sum())


array([ 0.        ,  4.64158883, 66.66666667])

0.16006721889793019

B7.2.3.3 Задание
1 point possible (graded)
Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [13]:
my_array=great_secret[great_secret>50]
display((my_array))
display(my_array.sum())

array([66.66666667, 67.33333333, 68.        , 68.66666667, 69.33333333,
       70.        , 70.66666667, 71.33333333, 72.        , 72.66666667,
       73.33333333, 74.        , 74.66666667, 75.33333333, 76.        ,
       76.66666667, 77.33333333, 78.        , 78.66666667, 79.33333333,
       80.        , 80.66666667, 81.33333333, 82.        , 82.66666667,
       83.33333333, 84.        , 50.4       , 84.66666667, 50.8       ,
       85.33333333, 51.2       , 86.        , 51.6       , 86.66666667,
       52.        , 87.33333333, 52.4       , 88.        , 52.8       ,
       88.66666667, 53.2       , 89.33333333, 53.6       , 90.        ,
       54.        , 90.66666667, 54.4       , 91.33333333, 54.8       ,
       92.        , 55.2       , 92.66666667, 55.6       , 93.33333333,
       56.        , 94.        , 56.4       , 94.66666667, 56.8       ,
       95.33333333, 57.2       , 96.        , 57.6       , 96.66666667,
       58.        , 97.33333333, 58.4       , 98.        , 58.8 

5470.0

B7.2.3.4 Задание
1 point possible (graded)
Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [14]:
my_array = great_secret.flatten()
display(my_array[150])


7.0710678118654755

B7.2.3.5 Задание
1 point possible (graded)
Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [16]:
my_array = np.sort(great_secret, axis=0)
display(my_array[-1,].sum())

115.12148016521353

ID (номер в журнале)	Рост, см	Масса тела, кг	Средний балл
1	135	34	4
2	160	43	5
3	163	40	4.3
4	147	44	5
5	138	41	4.7
6	149	54	3.9
7	136	39	4.2
8	154	48	4.9
9	137	35	3.7
10	165	60	4.6

Создайте массив, содержащий эти данные, и сохраните его под именем students.

In [20]:
students=np.array([[1,135,34,4],[2,160,43,5],[3,163,40,4.3],[4,147,44,5],[5,138,41,4.7],
                   [6,149,54,3.9],[7,136,39,4.2],[8,154,48,4.9],[9,137,35,3.7],[10,165,60,4.6]])
display(students)

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

Чему равно медианное значение массы тела школьников?

In [22]:
med_mass=np.median(students[:,2])
display(med_mass)

42.0

B7.3.1.2 Задание
1 point possible (graded)
На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [23]:
med_mass=np.median(students[:,2])
mean_mass=np.mean(students[:,2])
display(mean_mass-med_mass)

1.7999999999999972

B7.3.1.3 Задание
1 point possible (graded)
Между какой парой признаков в массиве students наблюдается минимальная корреляция?

In [25]:
corr_mass = np.corrcoef(students[:,1], students[:,2])
display(corr_mass)
corr_ball = np.corrcoef(students[:,1], students[:,3])
corr_mass_ball=np.corrcoef(students[:,2], students[:,3])
display(corr_mass)
display(corr_ball)
display(corr_mass_ball)


array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.

In [26]:
std_ball = np.std(students[:,3])
display(std_ball)

0.4517742799230607

Посчитайте, чему равна дисперсия значений веса школьников.
Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

In [27]:
var_wight = np.var(students[:,2])
display(var_wight)

60.36

B7.4.1.5 Задание
1 point possible (graded)
Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.

In [29]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin=np.sin(my_array)
display(my_sin.sum())


-0.05812430261413351

B7.4.1.6 Задание
1 point possible (graded)
Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

In [30]:
display(my_sin)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [36]:
my_sin[1:4,1:4]=np.array([[1,1,1],
                     [1,1,1],
                     [1,1,1]])
display(my_sin)
display(my_sin.sum())

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

7.571718421269144

B7.4.1.7 Задание
1 point possible (graded)
Преобразуйте первые четыре столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после точки-разделителя. Используйте преобразованный в предыдущем задании массив my_sin.

In [42]:
mask = np.array([1, 1, 1, 1,0], dtype=bool)
my_syn=my_sin[:, mask]
display(my_syn)
#my_array.reshape((4,5))
my_s=my_syn.reshape((10,2))
display(my_s)
#mask = np.array([1,0], dtype=bool)
my_sinn = my_s[:, 0]
display(my_sinn.sum())

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ,  1.        ,  1.        ],
       [-0.99999021,  1.        ,  1.        ,  1.        ],
       [-0.28790332,  1.        ,  1.        ,  1.        ],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

2.4057172058139544

In [ ]:
Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

B7.4.1.8 Задание
1 point possible (graded)
Чему равна медиана массива bigdata?

In [44]:
bigdata = [x**(2) for x in range(101,1001,2)]
display(np.median(bigdata))

302501.0

B7.4.1.9 Задание
1 point possible (graded)
Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:

In [45]:
display(np.std(bigdata))

292095.0301991155

In [46]:
display(np.shape(bigdata))

(450,)

B7.4.1.10 Задание
1 point possible (graded)
Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? Введите полученный ответ без изменений и округлений.

In [51]:
b=np.array([bigdata])
bd = b.reshape((225,2))
#display(bd)
display(np.corrcoef(bd[0,:], bd[1,:]))

array([[1., 1.],
       [1., 1.]])